name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    env:
      PREFIX: "/usr/local/"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.11"  #  >=3.8 <3.12
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp* *musl* "  # cp311-macosx*
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_LINUX: "auto"
          CIBW_BEFORE_ALL_MACOS: |
            mkdir -p /usr/local/include
            wget -O /usr/local/include/longintrepr.h https://github.com/python/cpython/blob/main/Include/cpython/longintrepr.h
            bash ci/osx-deps
          CIBW_BEFORE_ALL_LINUX:
            #wget -O /usr/local/include/longintrepr.h https://github.com/python/cpython/blob/main/Include/cpython/longintrepr.h
            bash ci/manylinux-deps
          CIBW_BEFORE_BUILD_MACOS: |
            ls -lh /usr/local/include/*
            echo "-----" && \
            ls -lh /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/*
            CFLAGS+="-I/usr/local/include" pip install -r requirements.txt
          CIBW_BEFORE_BUILD_LINUX: pip install -r requirements.txt
          CIBW_TEST_SKIP: "*-macosx_arm64"
          CIBW_TEST_REQUIRES: cython click>=8.0 numpy scipy pandas pysam==0.22.0 networkx>=2.4 scikit-learn>=0.22 edlib sortedcontainers lightgbm
          CIBW_TEST_COMMAND: dysgu test --verbose
          
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
